name: Update S&P 500 Stock Data

on:
  schedule:
    - cron: "0 * * * *"   # כל שעה
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install yfinance

      - name: Fetch stock data
        run: python scripts/fetch_stocks.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/stocks.json
          git commit -m "Hourly stock data update" || echo "No changes"
          git push
